### ISSUE TITLE
Feb 17, 2017 problem with cellular

### ISSUE THREAD

**Issue by andr68rus** [LineageOS/android_device_leeco_x2#1]
Camera work now, but there are problem with cellular:
1. Seeking network is very-very slow (up to 1 min)
Seeking up to 1 min, than in logcat:
02-17 21:06:17.250  2291  2426 D RILJ    : NOTE: mWakeLockCount is 1at time of clearing
02-17 21:06:17.253  2291  2426 D RILJ    : WAKE_LOCK_TIMEOUT  mRequestList=1
02-17 21:06:17.253  2291  2426 D RILJ    : 0: [20] RADIO_POWER
And phone got signal.
2. Cellular data does not work.
3. Dialing does not work at all when selinux is enforcing.

**Comment by mikeysteele** [comment]
I just did a build off these sources, and I have another bug. When a call comes in, the notification to answer the call isn't displayed so there is no way to answer.  Logcat shows the phone is definitely receiving the call.  I can't see anything in there that indicates what's causing the issue but then again I don't really know what I'm looking for.  The same error happens in a build I have from the 7th Feb.

**Comment by andr68rus** [comment]
mike, what os did you build? I build RR, and when I disable selinux in kernel options in boardconfig it seems working.

**Comment by mikeysteele** [comment]
I'm building LineageOS. The phone definitely receives the call, it just doesn't display the UI to answer it.
